[package]
name = "wgpu-misc"
version = "0.1.0"
authors = ["Mikko Lehtonen <scoopr@iki.fi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["async", "framebuffer"]
async = ["futures-executor", "wasm-bindgen-futures"]
framebuffer = ["raw-window-handle"]

[dev-dependencies]
winit = { version = "0.24.0", features = ["web-sys"] }
env_logger = "0.8.3"

[dependencies]
wgpu = "0.8.0"
raw-window-handle = { version = "0.3.3", optional = true }

# Native deps
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
futures-executor = { version = "0.3.14", optional = true }

# Wasm deps
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = { version = "0.4.23", optional = true }
