[package]
name = "wgpu-util"
version = "0.1.0"
authors = ["Mikko Lehtonen <scoopr@iki.fi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default=[]
wgpu-master=["wgpu-master-dep"]
wgpu-05=["wgpu-05-dep"]


[dependencies]

[dependencies.wgpu-master-dep]
package="wgpu"
git="https://github.com/gfx-rs/wgpu-rs"
optional=true

[dependencies.wgpu-05-dep]
package="wgpu"
version="0.5"
optional=true

# Native deps
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
futures="0.3"

# Wasm deps
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.12"
