[package]
name = "wgpu-util"
version = "0.1.0"
authors = ["Mikko Lehtonen <scoopr@iki.fi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
winit= { version = "0.24.0", features = ["web-sys"] }
env_logger= "0.8.3"

[dependencies]
wgpu={ git="https://github.com/gfx-rs/wgpu-rs", version="0.7" }
# wgpu={ version="0.7" }
raw-window-handle = "0.3.3"

# Native deps
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
futures= "0.3.14"

# Wasm deps
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.12"
